### ISSUE TITLE
Tokenize param field name under iteration documents for allowing aggregations

### ISSUE THREAD

**Issue by gurbirkalsi** [distributed-system-analysis/CommonDataModel#4]
In order to enable parameter filtering of iteration ids in benchpress dashboard, we require tokenization of parameter fields for appropriate aggregation of data. Ideally, this should be a single depth tokenization of the parameters so that we maintain the arg and value passed as one returned value.

**Comment by atheurer** [comment]
This should be addressed with https://github.com/distributed-system-analysis/CommonDataModel/pull/5
